//
//  CountryPickerModel.swift
//  BankNote_SwiftUI
//
//  Created by FIT on 07/09/2025.
//

import Foundation

struct Country: Identifiable, Hashable {
    let id = UUID()
    let nameKey: String  // localization key
    let code: String
    let flag: String

    var localizedName: String {
        NSLocalizedString(nameKey, comment: "")
    }
    
}

let countries: [Country] = [
    Country(nameKey: "Afghanistan", code: "+93", flag: "🇦🇫"),
    Country(nameKey: "Åland Islands", code: "+358", flag: "🇦🇽"),
    Country(nameKey: "Albania", code: "+355", flag: "🇦🇱"),
    Country(nameKey: "Algeria", code: "+213", flag: "🇩🇿"),
    Country(nameKey: "American Samoa", code: "+1-684", flag: "🇦🇸"),
    Country(nameKey: "Andorra", code: "+376", flag: "🇦🇩"),
    Country(nameKey: "Angola", code: "+244", flag: "🇦🇴"),
    Country(nameKey: "Anguilla", code: "+1-264", flag: "🇦🇮"),
    Country(nameKey: "Antarctica", code: "+672", flag: "🇦🇶"),
    Country(nameKey: "Antigua and Barbuda", code: "+1-268", flag: "🇦🇬"),
    Country(nameKey: "Argentina", code: "+54", flag: "🇦🇷"),
    Country(nameKey: "Armenia", code: "+374", flag: "🇦🇲"),
    Country(nameKey: "Aruba", code: "+297", flag: "🇦🇼"),
    Country(nameKey: "Australia", code: "+61", flag: "🇦🇺"),
    Country(nameKey: "Austria", code: "+43", flag: "🇦🇹"),
    Country(nameKey: "Azerbaijan", code: "+994", flag: "🇦🇿"),
    Country(nameKey: "Bahamas", code: "+1-242", flag: "🇧🇸"),
    Country(nameKey: "Bahrain", code: "+973", flag: "🇧🇭"),
    Country(nameKey: "Bangladesh", code: "+880", flag: "🇧🇩"),
    Country(nameKey: "Barbados", code: "+1-246", flag: "🇧🇧"),
    Country(nameKey: "Belarus", code: "+375", flag: "🇧🇾"),
    Country(nameKey: "Belgium", code: "+32", flag: "🇧🇪"),
    Country(nameKey: "Belize", code: "+501", flag: "🇧🇿"),
    Country(nameKey: "Benin", code: "+229", flag: "🇧🇯"),
    Country(nameKey: "Bermuda", code: "+1-441", flag: "🇧🇲"),
    Country(nameKey: "Bhutan", code: "+975", flag: "🇧🇹"),
    Country(nameKey: "Bolivia", code: "+591", flag: "🇧🇴"),
    Country(nameKey: "Bosnia and Herzegovina", code: "+387", flag: "🇧🇦"),
    Country(nameKey: "Botswana", code: "+267", flag: "🇧🇼"),
    Country(nameKey: "Brazil", code: "+55", flag: "🇧🇷"),
    Country(nameKey: "Brunei Darussalam", code: "+673", flag: "🇧🇳"),
    Country(nameKey: "Bulgaria", code: "+359", flag: "🇧🇬"),
    Country(nameKey: "Burkina Faso", code: "+226", flag: "🇧🇫"),
    Country(nameKey: "Burundi", code: "+257", flag: "🇧🇮"),
    Country(nameKey: "Cambodia", code: "+855", flag: "🇰🇭"),
    Country(nameKey: "Cameroon", code: "+237", flag: "🇨🇲"),
    Country(nameKey: "Canada", code: "+1", flag: "🇨🇦"),
    Country(nameKey: "Cape Verde", code: "+238", flag: "🇨🇻"),
    Country(nameKey: "Cayman Islands", code: "+1-345", flag: "🇰🇾"),
    Country(nameKey: "Central African Republic", code: "+236", flag: "🇨🇫"),
    Country(nameKey: "Chad", code: "+235", flag: "🇹🇩"),
    Country(nameKey: "Chile", code: "+56", flag: "🇨🇱"),
    Country(nameKey: "China", code: "+86", flag: "🇨🇳"),
    Country(nameKey: "Colombia", code: "+57", flag: "🇨🇴"),
    Country(nameKey: "Comoros", code: "+269", flag: "🇰🇲"),
    Country(nameKey: "Congo", code: "+242", flag: "🇨🇬"),
    Country(nameKey: "Congo, Democratic Republic of the", code: "+243", flag: "🇨🇩"),
    Country(nameKey: "Costa Rica", code: "+506", flag: "🇨🇷"),
    Country(nameKey: "Croatia", code: "+385", flag: "🇭🇷"),
    Country(nameKey: "Cuba", code: "+53", flag: "🇨🇺"),
    Country(nameKey: "Cyprus", code: "+357", flag: "🇨🇾"),
    Country(nameKey: "Czech Republic", code: "+420", flag: "🇨🇿"),
    Country(nameKey: "Denmark", code: "+45", flag: "🇩🇰"),
    Country(nameKey: "Djibouti", code: "+253", flag: "🇩🇯"),
    Country(nameKey: "Dominica", code: "+1-767", flag: "🇩🇲"),
    Country(nameKey: "Dominican Republic", code: "+1-809", flag: "🇩🇴"),
    Country(nameKey: "Ecuador", code: "+593", flag: "🇪🇨"),
    Country(nameKey: "Egypt", code: "+20", flag: "🇪🇬"),
    Country(nameKey: "El Salvador", code: "+503", flag: "🇸🇻"),
    Country(nameKey: "Estonia", code: "+372", flag: "🇪🇪"),
    Country(nameKey: "Ethiopia", code: "+251", flag: "🇪🇹"),
    Country(nameKey: "Fiji", code: "+679", flag: "🇫🇯"),
    Country(nameKey: "Finland", code: "+358", flag: "🇫🇮"),
    Country(nameKey: "France", code: "+33", flag: "🇫🇷"),
    Country(nameKey: "Germany", code: "+49", flag: "🇩🇪"),
    Country(nameKey: "Ghana", code: "+233", flag: "🇬🇭"),
    Country(nameKey: "Greece", code: "+30", flag: "🇬🇷"),
    Country(nameKey: "Greenland", code: "+299", flag: "🇬🇱"),
    Country(nameKey: "Guatemala", code: "+502", flag: "🇬🇹"),
    Country(nameKey: "Haiti", code: "+509", flag: "🇭🇹"),
    Country(nameKey: "Honduras", code: "+504", flag: "🇭🇳"),
    Country(nameKey: "Hong Kong", code: "+852", flag: "🇭🇰"),
    Country(nameKey: "Hungary", code: "+36", flag: "🇭🇺"),
    Country(nameKey: "Iceland", code: "+354", flag: "🇮🇸"),
    Country(nameKey: "India", code: "+91", flag: "🇮🇳"),
    Country(nameKey: "Indonesia", code: "+62", flag: "🇮🇩"),
    Country(nameKey: "Iran", code: "+98", flag: "🇮🇷"),
    Country(nameKey: "Iraq", code: "+964", flag: "🇮🇶"),
    Country(nameKey: "Ireland", code: "+353", flag: "🇮🇪"),
    Country(nameKey: "Israel", code: "+972", flag: "🇮🇱"),
    Country(nameKey: "Italy", code: "+39", flag: "🇮🇹"),
    Country(nameKey: "Jamaica", code: "+1-876", flag: "🇯🇲"),
    Country(nameKey: "Japan", code: "+81", flag: "🇯🇵"),
    Country(nameKey: "Jordan", code: "+962", flag: "🇯🇴"),
    Country(nameKey: "Kazakhstan", code: "+7", flag: "🇰🇿"),
    Country(nameKey: "Kenya", code: "+254", flag: "🇰🇪"),
    Country(nameKey: "Kuwait", code: "+965", flag: "🇰🇼"),
    Country(nameKey: "Kyrgyzstan", code: "+996", flag: "🇰🇬"),
    Country(nameKey: "Latvia", code: "+371", flag: "🇱🇻"),
    Country(nameKey: "Lebanon", code: "+961", flag: "🇱🇧"),
    Country(nameKey: "Libya", code: "+218", flag: "🇱🇾"),
    Country(nameKey: "Lithuania", code: "+370", flag: "🇱🇹"),
    Country(nameKey: "Luxembourg", code: "+352", flag: "🇱🇺"),
    Country(nameKey: "Macau", code: "+853", flag: "🇲🇴"),
    Country(nameKey: "Madagascar", code: "+261", flag: "🇲🇬"),
    Country(nameKey: "Malawi", code: "+265", flag: "🇲🇼"),
    Country(nameKey: "Malaysia", code: "+60", flag: "🇲🇾"),
    Country(nameKey: "Maldives", code: "+960", flag: "🇲🇻"),
    Country(nameKey: "Mali", code: "+223", flag: "🇲🇱"),
    Country(nameKey: "Malta", code: "+356", flag: "🇲🇹"),
    Country(nameKey: "Mauritania", code: "+222", flag: "🇲🇷"),
    Country(nameKey: "Mauritius", code: "+230", flag: "🇲🇺"),
    Country(nameKey: "Mexico", code: "+52", flag: "🇲🇽"),
    Country(nameKey: "Moldova", code: "+373", flag: "🇲🇩"),
    Country(nameKey: "Monaco", code: "+377", flag: "🇲🇨"),
    Country(nameKey: "Mongolia", code: "+976", flag: "🇲🇳"),
    Country(nameKey: "Montenegro", code: "+382", flag: "🇲🇪"),
    Country(nameKey: "Morocco", code: "+212", flag: "🇲🇦"),
    Country(nameKey: "Mozambique", code: "+258", flag: "🇲🇿"),
    Country(nameKey: "Myanmar", code: "+95", flag: "🇲🇲"),
    Country(nameKey: "Namibia", code: "+264", flag: "🇳🇦"),
    Country(nameKey: "Nepal", code: "+977", flag: "🇳🇵"),
    Country(nameKey: "Netherlands", code: "+31", flag: "🇳🇱"),
    Country(nameKey: "New Zealand", code: "+64", flag: "🇳🇿"),
    Country(nameKey: "Nicaragua", code: "+505", flag: "🇳🇮"),
    Country(nameKey: "Niger", code: "+227", flag: "🇳🇪"),
    Country(nameKey: "Nigeria", code: "+234", flag: "🇳🇬"),
    Country(nameKey: "North Korea", code: "+850", flag: "🇰🇵"),
    Country(nameKey: "Norway", code: "+47", flag: "🇳🇴"),
    Country(nameKey: "Oman", code: "+968", flag: "🇴🇲"),
    Country(nameKey: "Pakistan", code: "+92", flag: "🇵🇰"),
    Country(nameKey: "Palestine", code: "+970", flag: "🇵🇸"),
    Country(nameKey: "Panama", code: "+507", flag: "🇵🇦"),
    Country(nameKey: "Paraguay", code: "+595", flag: "🇵🇾"),
    Country(nameKey: "Peru", code: "+51", flag: "🇵🇪"),
    Country(nameKey: "Philippines", code: "+63", flag: "🇵🇭"),
    Country(nameKey: "Poland", code: "+48", flag: "🇵🇱"),
    Country(nameKey: "Portugal", code: "+351", flag: "🇵🇹"),
    Country(nameKey: "Puerto Rico", code: "+1-787", flag: "🇵🇷"),
    Country(nameKey: "Qatar", code: "+974", flag: "🇶🇦"),
    Country(nameKey: "Romania", code: "+40", flag: "🇷🇴"),
    Country(nameKey: "Russia", code: "+7", flag: "🇷🇺"),
    Country(nameKey: "Rwanda", code: "+250", flag: "🇷🇼"),
    Country(nameKey: "Saudi Arabia", code: "+966", flag: "🇸🇦"),
    Country(nameKey: "Senegal", code: "+221", flag: "🇸🇳"),
    Country(nameKey: "Serbia", code: "+381", flag: "🇷🇸"),
    Country(nameKey: "Seychelles", code: "+248", flag: "🇸🇨"),
    Country(nameKey: "Sierra Leone", code: "+232", flag: "🇸🇱"),
    Country(nameKey: "Singapore", code: "+65", flag: "🇸🇬"),
    Country(nameKey: "Slovakia", code: "+421", flag: "🇸🇰"),
    Country(nameKey: "Slovenia", code: "+386", flag: "🇸🇮"),
    Country(nameKey: "Somalia", code: "+252", flag: "🇸🇴"),
    Country(nameKey: "South Africa", code: "+27", flag: "🇿🇦"),
    Country(nameKey: "South Korea", code: "+82", flag: "🇰🇷"),
    Country(nameKey: "Spain", code: "+34", flag: "🇪🇸"),
    Country(nameKey: "Sri Lanka", code: "+94", flag: "🇱🇰"),
    Country(nameKey: "Sudan", code: "+249", flag: "🇸🇩"),
    Country(nameKey: "Suriname", code: "+597", flag: "🇸🇷"),
    Country(nameKey: "Sweden", code: "+46", flag: "🇸🇪"),
    Country(nameKey: "Switzerland", code: "+41", flag: "🇨🇭"),
    Country(nameKey: "Syria", code: "+963", flag: "🇸🇾"),
    Country(nameKey: "Taiwan", code: "+886", flag: "🇹🇼"),
    Country(nameKey: "Tajikistan", code: "+992", flag: "🇹🇯"),
    Country(nameKey: "Tanzania", code: "+255", flag: "🇹🇿"),
    Country(nameKey: "Thailand", code: "+66", flag: "🇹🇭"),
    Country(nameKey: "Tunisia", code: "+216", flag: "🇹🇳"),
    Country(nameKey: "Turkey", code: "+90", flag: "🇹🇷"),
    Country(nameKey: "Turkmenistan", code: "+993", flag: "🇹🇲"),
    Country(nameKey: "Uganda", code: "+256", flag: "🇺🇬"),
    Country(nameKey: "Ukraine", code: "+380", flag: "🇺🇦"),
    Country(nameKey: "United Arab Emirates", code: "+971", flag: "🇦🇪"),
    Country(nameKey: "United Kingdom", code: "+44", flag: "🇬🇧"),
    Country(nameKey: "United States", code: "+1", flag: "🇺🇸"),
    Country(nameKey: "Uruguay", code: "+598", flag: "🇺🇾"),
    Country(nameKey: "Uzbekistan", code: "+998", flag: "🇺🇿"),
    Country(nameKey: "Venezuela", code: "+58", flag: "🇻🇪"),
    Country(nameKey: "Vietnam", code: "+84", flag: "🇻🇳"),
    Country(nameKey: "Yemen", code: "+967", flag: "🇾🇪"),
    Country(nameKey: "Zambia", code: "+260", flag: "🇿🇲"),
    Country(nameKey: "Zimbabwe", code: "+263", flag: "🇿🇼"),
]
